os:
  - linux
language: node_js
node_js:
  # - "4.1" Not working with Travis-CI
  # - "4.0" Not working with Travis-CI
  - "0.12"
  - "0.11"
  - "0.10"
env:
  - NODE_ENV=test
script:
  - npm test
services:
  - mongodb
